# Generated by Django 4.2.3 on 2023-11-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registered',
        ),
        migrations.AddField(
            model_name='event_registration',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
