# Generated by Django 4.2.3 on 2023-11-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_registered_event_registration_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_registration',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
    ]
