# Generated by Django 4.2.3 on 2023-11-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_event_event_registration_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registered_user',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
