# Generated by Django 4.2.3 on 2023-11-28 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0010_remove_event_user_event_registration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_registration',
            name='user',
        ),
        migrations.AddField(
            model_name='event_registration',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
