# Generated by Django 4.2.3 on 2023-11-28 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0014_remove_event_user_remove_event_registration_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='users',
        ),
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
